# Generated by Django 3.2.16 on 2023-09-06 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    replaces = [('chat', '0001_initial'), ('chat', '0002_alter_chat_messages'), ('chat', '0003_alter_chat_messages'), ('chat', '0004_alter_userchat_time_created'), ('chat', '0005_alter_chat_options_alter_userchat_options_and_more'), ('chat', '0006_auto_20230807_1717'), ('chat', '0007_auto_20230807_1717'), ('chat', '0008_auto_20230808_1254'), ('chat', '0009_alter_message_time_sending'), ('chat', '0010_auto_20230819_1947'), ('chat', '0011_alter_message_time_sending_timestamp'), ('chat', '0012_auto_20230820_1427'), ('chat', '0013_auto_20230820_2217'), ('chat', '0014_alter_chat_last_message'), ('chat', '0015_alter_message_sending_timestamp'), ('chat', '0016_auto_20230824_1405'), ('chat', '0017_alter_chat_last_message'), ('chat', '0018_remove_chat_status'), ('chat', '0019_chat_status'), ('chat', '0020_message_file'), ('chat', '0021_alter_message_file'), ('chat', '0022_alter_message_file'), ('chat', '0023_remove_message_file'), ('chat', '0024_auto_20230901_2208'), ('chat', '0025_alter_messagefile_image')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now=True, verbose_name='время создания чата')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='users.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='users.user')),
                ('last_message', models.TextField(default='', verbose_name='последнее сообщение')),
                ('status', models.TextField(default=None, null=True, verbose_name='статус, например, что пользователь печатает')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст сообщения')),
                ('is_read', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='chat.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('sending_timestamp', core.models.TimestampField(blank=True, editable=False, verbose_name='время отправки сообщения')),
            ],
            options={
                'ordering': ['sending_timestamp'],
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lm', to='chat.message', verbose_name='последнее сообщение'),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='time_created',
        ),
        migrations.AddField(
            model_name='chat',
            name='created_timestamp',
            field=core.models.TimestampField(blank=True, default=0, editable=False, verbose_name='время создания чата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message', to='chat.message', verbose_name='последнее сообщение'),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='status',
        ),
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.JSONField(default=dict, verbose_name='статус, например, что пользователь печатает'),
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='chat_images/%Y/%m/%d', verbose_name='фотография')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.messagefile'),
        ),
    ]
