# Generated by Django 4.2.4 on 2023-08-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.JSONField(default={}),
        ),
    ]
