# Generated by Django 3.2.16 on 2024-04-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20240406_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('sending_timestamp', 'pk'), 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
