# Generated by Django 4.2.4 on 2023-08-06 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_userchat_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='userchat',
            options={'verbose_name': 'Пользователи - чат', 'verbose_name_plural': 'Пользователи - чаты'},
        ),
        migrations.AlterField(
            model_name='userchat',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='chat.chat'),
        ),
    ]
