# Generated by Django 3.2.16 on 2023-08-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20230807_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'чат', 'verbose_name_plural': 'чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['time_sending'], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
