# Generated by Django 3.2.16 on 2023-08-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20230808_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_sending',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время отправки сообщения'),
        ),
    ]
