# Generated by Django 3.2.16 on 2023-08-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20230819_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_sending_timestamp',
            field=models.PositiveBigIntegerField(verbose_name='время отправки сообщения'),
        ),
    ]
