# Generated by Django 3.2.16 on 2023-08-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_message_time_sending_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sending_timestamp'], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='time_sending_timestamp',
            new_name='sending_timestamp',
        ),
    ]
