# Generated by Django 3.2.16 on 2023-08-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20230820_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.TextField(default='', verbose_name='последнее сообщение'),
        ),
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.TextField(default=None, null=True, verbose_name='статус, например, что пользователь печатает'),
        ),
    ]
