# Generated by Django 3.2.16 on 2023-08-24 10:03

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_chat_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sending_timestamp',
            field=core.models.TimestampField(blank=True, editable=False, verbose_name='время отправки сообщения'),
        ),
    ]
