# Generated by Django 3.2.16 on 2023-08-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_remove_chat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.JSONField(default=dict, verbose_name='статус, например, что пользователь печатает'),
        ),
    ]
