# Generated by Django 3.2.16 on 2023-09-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_chat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='прикрепленный файл'),
        ),
    ]
