# Generated by Django 3.2.16 on 2023-09-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_alter_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
