# Generated by Django 3.2.16 on 2023-09-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_auto_20230901_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefile',
            name='image',
            field=models.ImageField(null=True, upload_to='chat_images/%Y/%m/%d', verbose_name='фотография'),
        ),
    ]
