# Generated by Django 3.2.16 on 2023-08-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Напишите немного о себе', null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберете фотографию профиля', null=True, upload_to='', verbose_name='Фотография'),
        ),
    ]
