# Generated by Django 3.2.16 on 2023-08-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230807_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Напишите немного о себе', null=True, verbose_name='о себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберете фотографию профиля', null=True, upload_to='', verbose_name='фотография'),
        ),
    ]
