# Generated by Django 3.2.16 on 2023-08-08 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230807_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='последний раз онлайн'),
        ),
    ]
