# Generated by Django 3.2.16 on 2023-08-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230822_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/%Y/%m/%d', verbose_name='фотография'),
        ),
    ]
