name: Python | flake8 & black

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements/requirements-prod.txt
        pip install -r backend/requirements/requirements-dev.txt
        pip install -r backend/requirements/requirements-test.txt
    - name: flake8 Lint
      uses: py-actions/flake8@v2
      with:
        plugins: 'flake8-import-order flake8-quotes'
    - name: Lint with black
      uses: psf/black@stable
      with:
        options: '--check --verbose'
        version: '~= 22.0'


